@apiGateway = http://localhost:3001/api

@other = http://localhost:3003

@bearerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMDk1MTE5ZS1hOGY5LTQ4NTAtOGIyNS04ZTQ4NmNmNzQwNDQiLCJpYXQiOjE3NjIwNTAyNzQsImV4cCI6MTc2MjA1MTE3NH0.FtZfJKhWt9jwV6-KCyuscdX2TbIkgoLJe9HnT1ORKIo

### Auth register
POST {{apiGateway}}/auth/register
Content-Type: application/json
Accept: application/json

{
  "name": "Marlon Lima",
  "email": "marlon@example.com",
  "password": "123456"
}


### Auth login
POST {{apiGateway}}/auth/login
Content-Type: application/json

{
  "email": "lety@example.com",
  "password": "1234565"
}

### Auth refresh
# @name authRefresh
POST {{apiGateway}}/auth/refresh
Content-Type: application/json
Accept: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMDk1MTE5ZS1hOGY5LTQ4NTAtOGIyNS04ZTQ4NmNmNzQwNDQiLCJpYXQiOjE3NjE4NDQyNTgsImV4cCI6MTc2MjQ0OTA1OH0.Nkh3xY_lKcReKuSgcwzNGzlF2ChXZ_wVkqqgJ8UQCr8"
}

### Set token variable
@token = {{authRefresh.response.body.token}}

### Auth Me
GET {{apiGateway}}/auth/me
Content-Type: application/json
Authorization: Bearer {{token}}


### Auth refresh
POST {{apiGateway}}/tasks
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "task_name": "Task name example"
}

### FIND TASKS
GET {{other}}/tasks
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}


### CREATE TASK
POST {{other}}/tasks
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "title": "Create responsive task cards",
  "description": "Implement grid layout and mobile breakpoints for task cards layout.",
  "dueDate": "2025-11-10T00:00:00.000Z",
  "priority": "LOW",
  "status": "TODO"
}

### FIND BY ID
GET {{other}}/tasks/689601f3-5dac-4179-830e-091f42572f5e
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### UPDATE TASK
PUT {{other}}/tasks/689601f3-5dac-4179-830e-091f42572f5e
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "title": "Escrever documentação da API 333"
}
