@apiGateWayUrl=http://localhost:3003/auth


### Register user
POST {{apiGateWayUrl}}/users
Content-Type: application/json
Accept: application/json

{
  "name": "Lucylenne Pereira",
  "email": "lucylenne@example.com",
  "password": "123456"
}


### Auth user
POST {{apiGateWayUrl}}/login
Content-Type: application/json
Accept: application/json

{ 
  "email": "augustojaml@example.com",
  "password": "123456"
}
