enum ErrorCodes {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  GENERIC_ERROR = 'GENERIC_ERROR',
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
  INVALID_STATUS_TYPE = 'INVALID_STATUS_TYPE',
  INVALID_BID_AMOUNT = 'INVALID_BID_AMOUNT',
}

export { ErrorCodes }
